package org.springframework.samples.petclinic.pet.create.keyboard;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

public class CreatePetKeyboard {

	private final WebDriver driver;

	JavascriptExecutor js;

	public CreatePetKeyboard(WebDriver driver) {
		this.driver = driver;
	}

	@Before
	public void setUp() {
		js = (JavascriptExecutor) driver;
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void createPetKeyboardSource() {
		driver.get("http://localhost:8080/");
		driver.manage().window().maximize();
		driver.findElement(By.cssSelector("li:nth-child(2) > a")).click();
		driver.findElement(By.id("lastName")).sendKeys("Rossi");
		driver.findElement(By.id("lastName")).sendKeys(Keys.ENTER);
		driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
		driver.findElement(By.id("name")).sendKeys("Source");
		driver.findElement(By.id("birthDate")).sendKeys("2020-10-10");
		{
			WebElement dropdown = driver.findElement(By.id("type"));
			dropdown.findElement(By.xpath("//option[. = 'cat']")).click();
		}
		{
			WebElement dropdown = driver.findElement(By.id("type"));
			dropdown.findElement(By.xpath("//option[. = 'dog']")).click();
		}
		driver.findElement(By.cssSelector(".btn")).click();
	}

}
