package org.springframework.samples.petclinic.pet.create.mouse;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.apache.commons.lang3.StringUtils.indexOfDifference;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;

public class CreatePetMouse {

	private final WebDriver driver;

	JavascriptExecutor js;

	public CreatePetMouse(WebDriver driver) {
		this.driver = driver;
	}

	@Before
	public void setUp() {
		js = (JavascriptExecutor) driver;
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void createPetMouseSource() throws InterruptedException {

		driver.get("http://localhost:8080/");
		driver.manage().window().maximize();
		// Finestra a dimensione massima
		driver.findElement(By.cssSelector("li:nth-child(2) span:nth-child(2)")).click();
		// Inserisce Rossi nella textField
		driver.findElement(By.id("lastName")).click();
		driver.findElement(By.id("lastName")).sendKeys("Rossi");
		driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
		// Pagina del proprietario animale (before)
		driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
		// Aggiungo l'animale
		driver.findElement(By.id("name")).click();
		driver.findElement(By.id("name")).sendKeys("Source");
		driver.findElement(By.id("birthDate")).click();
		driver.findElement(By.id("birthDate")).sendKeys("2020-10-10");
		driver.findElement(By.id("type")).click();
		{
			WebElement dropdown = driver.findElement(By.id("type"));
			dropdown.findElement(By.xpath("//option[. = 'dog']")).click();
		}
		driver.findElement(By.id("type")).click();
		// Pagina del proprietario animale (after)
		driver.findElement(By.cssSelector(".btn")).click();
	}

}

/*
 * private void nextTest(){ //Salva il percorso delle pagine in cont e termina il test
 * corrente List<String> pagesOfThisTest=null; if(driver instanceof ChromeDriverPage){
 * pagesOfThisTest=new ArrayList<>(((ChromeDriverPage)driver).htmlPages);
 * ((ChromeDriverPage) driver).htmlPages.clear(); } else if(driver instanceof
 * FirefoxDriverPage){ pagesOfThisTest=new
 * ArrayList<>(((FirefoxDriverPage)driver).htmlPages); ((FirefoxDriverPage)
 * driver).htmlPages.clear(); } //cont avrà tutte le liste delle pagine
 * cont.add(pagesOfThisTest); //chiudiamo la finestra del caso di test, inizia il prossimo
 * } }
 */
